name: Update README

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub Activity in README
        uses: JamesIves/github-activity-readme@v0.4.5
        with:
          REPOSITORY: juangrimaldos-png/juangrimaldos-png
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
